### ISSUE TITLE
Make hyperlinks clickable?

### ISSUE THREAD

**Issue by charlec** [calculist/calculist#19]
As the title says, can hyperlinks in lists be made clickable?

This would be useful when adding links for later review - in this particular case planning a holiday and keeping links for potential accommodation.

Thanks,
Chris

**Comment by danallison** [comment]
Hi Chris. I agree that this would be a useful feature. After doing a quick investigation into what it would take to get this working, it appears to be more complicated than one might expect, due to the fact that the content of an item is editable, and the current click behavior is to change the content from the "display" value to the "actual" value. My attempts to work around this have thus far failed.

As a workaround, there is a `follow link` command, which has the effect of clicking on the link. However, it opens the link in the current tab instead of a new tab, which isn't ideal.

For now, I am focusing on finishing the desktop app, and then other high priority tasks required before I can open the source code. So I will likely not get to this feature anytime soon, unfortunately.

**Comment by charlec** [comment]
Fair enough and thanks for looking into it.  The "follow link" work around is useful.

If detecting a hyperlink is easy could you do something like have a clickable symbol appear?
