### ISSUE TITLE
Command to permanently delete a list

### ISSUE THREAD

**Issue by nkallman** [calculist/calculist#9]
Currently using `delete` on the list of lists in the root list only removes its reference in that list.
If you use `goto list "MyDeletedList"` the list with all its data will still be there (and it will be re-added to the list of lists)

**Comment by danallison** [comment]
Eventually, you will be able to permanently delete a list from the UI. For the short term, you can email me the name of the list, and I can delete it for you. Email: dan@calculist.io

I have not implemented this feature yet because I want to make sure that it is clear that the action cannot be undone.

One idea is a command like 
```
permanently delete list "List Name"
```
that would show a confirmation dialogue before executing.

I will keep this issue open until the feature has been implemented.

**Comment by danallison** [comment]
Update: I went ahead and implemented this feature. You can now permanently delete a list with the command
```
permanently delete list "List Name"
```
